import process from "node:process";
import esbuild from "esbuild";

const builtins = [
	"assert",
	"buffer",
	"child_process",
	"cluster",
	"crypto",
	"dgram",
	"dns",
	"domain",
	"events",
	"fs",
	"http",
	"https",
	"net",
	"os",
	"path",
	"punycode",
	"querystring",
	"readline",
	"stream",
	"string_decoder",
	"timers",
	"tls",
	"tty",
	"url",
	"util",
	"v8",
	"vm",
	"zlib",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

export const prod = process.argv[2] === "production";
const baseConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	platform: "node",
	target: "ES6",
	logLevel: "info",
	treeShaking: true,
	outfile: "main.js",
};

if (prod) {
	await esbuild.build({
		...baseConfig,
		minify: true,
		sourcemap: false,
	});
	process.exit(0);
} else {
	const ctx = await esbuild.context({
		...baseConfig,
		minify: false,
		sourcemap: "inline",
	});
	await ctx.watch();
}
